[package]
name = "redis_manager"
version = "0.0.1"
description = "A cross-platform redis gui client"
authors = ["Makise_kurisuu@outlook.jp"]
license = "MIT"
repository = "https://github.com/kurisu994/Redis-Manager.git"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.2", features = [] }

[dependencies]
serde_json = "^1.0.94"
serde = { version = "^1.0.158", features = ["derive"] }
tauri = { version = "1.2", features = ["devtools", "shell-open", "system-tray"] }
diesel = { version = "^2.0.3", features = ["sqlite", "uuid"] }
diesel_migrations = { version = "^2.0.0", features = ["sqlite"] }
libsqlite3-sys = { version = "^0", features = ["bundled"] }

dotenv = "^0.15.0"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
default = [ "custom-protocol" ]
custom-protocol = ["tauri/custom-protocol"]
